version: '3.8'
services:
  fastapi-app:
    build: .
    container_name: python-server
    command: uvicorn app.main:app --host 0.0.0.0 --port 80 --reload
    network_mode: "host"
    ports:
      - "80:80"
    volumes:
      - /home/ben/social-arbjuration/app
    depends_on:
      - selenium-server

  selenium-server:
    image: selenium/standalone-chrome:latest
    ports:
      - "4444:4444"
